/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.7 .\jnrbox.glb --transform -F avif -R 4096 --types --keepnames --keepmeshes
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Cube010: THREE.SkinnedMesh;
    Cube010_1: THREE.SkinnedMesh;
    Cube010_2: THREE.SkinnedMesh;
    BOX_PLINTH: THREE.SkinnedMesh;
    Retopo_BOX_FILM: THREE.SkinnedMesh;
    DKFYB6: THREE.Mesh;
    DKFYB6_1: THREE.Mesh;
    DKFYB6_2: THREE.Mesh;
    DKFYB6_3: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002_1: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002_2: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002_3: THREE.Mesh;
    Merged_Apple002: THREE.Mesh;
    Merged_Apple002_1: THREE.Mesh;
    Merged_Apple002_2: THREE.Mesh;
    Merged_Apple002_3: THREE.Mesh;
    Merged_Apple002_4: THREE.Mesh;
    Merged_JNRS_HANDS1: THREE.Mesh;
    Merged_JNRS_HANDS1_1: THREE.Mesh;
    Merged_JNRS_HANDS1_2: THREE.Mesh;
    Merged_JNRS_HANDS1_3: THREE.Mesh;
    Merged_JNRS_HANDS1_4: THREE.Mesh;
    Merged_JNRS_HANDS1_5: THREE.Mesh;
    Merged_JNRS_HANDS1_6: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_1: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_2: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_3: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_4: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_5: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_6: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_7: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003_1: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003_2: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003_3: THREE.Mesh;
    Merged_Extract3: THREE.Mesh;
    Merged_Extract3_1: THREE.Mesh;
    Merged_Extract3_2: THREE.Mesh;
    Merged_Extract3_3: THREE.Mesh;
    Merged_Extract3_4: THREE.Mesh;
    ARMS_1: THREE.Mesh;
    ARMS_2: THREE.Mesh;
    BODY: THREE.Mesh;
    EYES001: THREE.Mesh;
    FEET: THREE.Mesh;
    Merged_Apple7006: THREE.Mesh;
    Merged_Apple7006_1: THREE.Mesh;
    PUPILS: THREE.Mesh;
    MAIN: THREE.Bone;
  };
  materials: {
    ["BOX MAIN"]: THREE.MeshStandardMaterial;
    ["Nacre (Nácar)"]: THREE.MeshStandardMaterial;
    ["BOX MAIN INSIDE"]: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshStandardMaterial;
    ["BOX FILM.001"]: THREE.MeshPhysicalMaterial;
    ["YELLOW ORANGE"]: THREE.MeshStandardMaterial;
    ["DARK GREY 3"]: THREE.MeshStandardMaterial;
    ["GREY DARK"]: THREE.MeshStandardMaterial;
    OH_Outline_Material: THREE.MeshBasicMaterial;
    ["GREEN EARTH DARK"]: THREE.MeshStandardMaterial;
    YELLOW: THREE.MeshStandardMaterial;
    ["GREEN EARTH"]: THREE.MeshStandardMaterial;
    ["OUTLINE GREEN"]: THREE.MeshBasicMaterial;
    ["SAND SHADING"]: THREE.MeshStandardMaterial;
    SAND: THREE.MeshStandardMaterial;
    ["OUTLINE RED"]: THREE.MeshStandardMaterial;
    RED: THREE.MeshStandardMaterial;
    WHITE: THREE.MeshStandardMaterial;
    GREY: THREE.MeshStandardMaterial;
    ORANGE: THREE.MeshStandardMaterial;
    ["HOT SKY BLUE"]: THREE.MeshStandardMaterial;
    ["GREEN LIGHT"]: THREE.MeshStandardMaterial;
    BRICK: THREE.MeshStandardMaterial;
    ["TENNIS BALL GREEN"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Animation";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

interface Props {
  groupProps?: JSX.IntrinsicElements["group"];
  scroll: React.MutableRefObject<number>;
}

export function JnrBox(props: Props) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/3d/jnrbox-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  const extras = { receiveShadow: true, castShadow: true };

  console.log("actions", Object.entries(actions)); // "Animation"

  useEffect(() => void (actions["Animation"].play().paused = true), []);

  useFrame((state) => {
    actions["Animation"].time = THREE.MathUtils.lerp(
      actions["Animation"].time,
      actions["Animation"].getClip().duration * props.scroll.current,
      0.05
    );
    group.current.children.forEach((child, index) => {
      const et = state.clock.elapsedTime;
      child.position.y = Math.sin((et + index * 2000) / 2) * 1;
      child.rotation.x = Math.sin((et + index * 2000) / 3) / 10;
      child.rotation.y = Math.cos((et + index * 2000) / 2) / 10;
      child.rotation.z = Math.sin((et + index * 2000) / 3) / 10;
    });
  });

  return (
    <group ref={group} {...props.groupProps} dispose={null}>
      <group name="Scene">
        <group name="BOX" position={[0, 2.85, -0.21]} scale={0.94}>
          <group name="BOX_OPENING">
            <primitive object={nodes.MAIN} />
            <group name="BOX_MAIN">
              <skinnedMesh
                name="Cube010"
                geometry={nodes.Cube010.geometry}
                material={materials["BOX MAIN"]}
                skeleton={nodes.Cube010.skeleton}
                {...extras}
              />
              <skinnedMesh
                name="Cube010_1"
                geometry={nodes.Cube010_1.geometry}
                material={materials["Nacre (Nácar)"]}
                skeleton={nodes.Cube010_1.skeleton}
                {...extras}
              />
              <skinnedMesh
                name="Cube010_2"
                geometry={nodes.Cube010_2.geometry}
                material={materials["BOX MAIN INSIDE"]}
                skeleton={nodes.Cube010_2.skeleton}
                {...extras}
              />
            </group>
            <skinnedMesh
              name="BOX_PLINTH"
              geometry={nodes.BOX_PLINTH.geometry}
              material={materials.Material}
              skeleton={nodes.BOX_PLINTH.skeleton}
              {...extras}
            />
            <skinnedMesh
              name="Retopo_BOX_FILM"
              geometry={nodes.Retopo_BOX_FILM.geometry}
              material={materials["BOX FILM.001"]}
              skeleton={nodes.Retopo_BOX_FILM.skeleton}
              {...extras}
            />
          </group>
          <group name="JNRS" position={[0, -3.02, 0.22]} scale={1.06}>
            <group
              name="BACKMUSICDRUMKIT"
              position={[0, 0.04, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="DKFYB6"
                geometry={nodes.DKFYB6.geometry}
                material={materials["YELLOW ORANGE"]}
                {...extras}
              />
              <mesh
                name="DKFYB6_1"
                geometry={nodes.DKFYB6_1.geometry}
                material={materials["DARK GREY 3"]}
                {...extras}
              />
              <mesh
                name="DKFYB6_2"
                geometry={nodes.DKFYB6_2.geometry}
                material={materials["GREY DARK"]}
                {...extras}
              />
              <mesh
                name="DKFYB6_3"
                geometry={nodes.DKFYB6_3.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
            </group>
            <group
              name="BOTTOMSHISTORYTREX"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="Merged_PM3D_SHORTS1_2002"
                geometry={nodes.Merged_PM3D_SHORTS1_2002.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
              <mesh
                name="Merged_PM3D_SHORTS1_2002_1"
                geometry={nodes.Merged_PM3D_SHORTS1_2002_1.geometry}
                material={materials["GREEN EARTH DARK"]}
                {...extras}
              />
              <mesh
                name="Merged_PM3D_SHORTS1_2002_2"
                geometry={nodes.Merged_PM3D_SHORTS1_2002_2.geometry}
                material={materials.YELLOW}
                {...extras}
              />
              <mesh
                name="Merged_PM3D_SHORTS1_2002_3"
                geometry={nodes.Merged_PM3D_SHORTS1_2002_3.geometry}
                material={materials["GREEN EARTH"]}
                {...extras}
              />
            </group>
            <group
              name="HEADMATHSPC"
              position={[0, 1.46, -0.2]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="Merged_Apple002"
                geometry={nodes.Merged_Apple002.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
              <mesh
                name="Merged_Apple002_1"
                geometry={nodes.Merged_Apple002_1.geometry}
                material={materials["OUTLINE GREEN"]}
                {...extras}
              />
              <mesh
                name="Merged_Apple002_2"
                geometry={nodes.Merged_Apple002_2.geometry}
                material={materials["SAND SHADING"]}
                {...extras}
              />
              <mesh
                name="Merged_Apple002_3"
                geometry={nodes.Merged_Apple002_3.geometry}
                material={materials.SAND}
                {...extras}
              />
              <mesh
                name="Merged_Apple002_4"
                geometry={nodes.Merged_Apple002_4.geometry}
                material={materials["OUTLINE RED"]}
                {...extras}
              />
            </group>
            <group
              name="LHMATHSCLOCK"
              position={[0, 0.04, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="Merged_JNRS_HANDS1"
                geometry={nodes.Merged_JNRS_HANDS1.geometry}
                material={materials.RED}
                {...extras}
              />
              <mesh
                name="Merged_JNRS_HANDS1_1"
                geometry={nodes.Merged_JNRS_HANDS1_1.geometry}
                material={materials.WHITE}
                {...extras}
              />
              <mesh
                name="Merged_JNRS_HANDS1_2"
                geometry={nodes.Merged_JNRS_HANDS1_2.geometry}
                material={materials["DARK GREY 3"]}
                {...extras}
              />
              <mesh
                name="Merged_JNRS_HANDS1_3"
                geometry={nodes.Merged_JNRS_HANDS1_3.geometry}
                material={materials.GREY}
                {...extras}
              />
              <mesh
                name="Merged_JNRS_HANDS1_4"
                geometry={nodes.Merged_JNRS_HANDS1_4.geometry}
                material={materials.WHITE}
                {...extras}
              />
              <mesh
                name="Merged_JNRS_HANDS1_5"
                geometry={nodes.Merged_JNRS_HANDS1_5.geometry}
                material={materials.YELLOW}
                {...extras}
              />
              <mesh
                name="Merged_JNRS_HANDS1_6"
                geometry={nodes.Merged_JNRS_HANDS1_6.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
            </group>
            <group
              name="RHMATHSRUBIKS"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="Merged_RUBIKS_WINGS_2011"
                geometry={nodes.Merged_RUBIKS_WINGS_2011.geometry}
                material={materials.WHITE}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_1"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_1.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_2"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_2.geometry}
                material={materials.ORANGE}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_3"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_3.geometry}
                material={materials.RED}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_4"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_4.geometry}
                material={materials.YELLOW}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_5"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_5.geometry}
                material={materials["HOT SKY BLUE"]}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_6"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_6.geometry}
                material={materials["DARK GREY 3"]}
                {...extras}
              />
              <mesh
                name="Merged_RUBIKS_WINGS_2011_7"
                geometry={nodes.Merged_RUBIKS_WINGS_2011_7.geometry}
                material={materials["GREEN LIGHT"]}
                {...extras}
              />
            </group>
            <group
              name="SHOESBIOLOGYTIGER"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="Merged_PM3D_Cylinder3D1_2003"
                geometry={nodes.Merged_PM3D_Cylinder3D1_2003.geometry}
                material={materials.BRICK}
                {...extras}
              />
              <mesh
                name="Merged_PM3D_Cylinder3D1_2003_1"
                geometry={nodes.Merged_PM3D_Cylinder3D1_2003_1.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
              <mesh
                name="Merged_PM3D_Cylinder3D1_2003_2"
                geometry={nodes.Merged_PM3D_Cylinder3D1_2003_2.geometry}
                material={materials["DARK GREY 3"]}
                {...extras}
              />
              <mesh
                name="Merged_PM3D_Cylinder3D1_2003_3"
                geometry={nodes.Merged_PM3D_Cylinder3D1_2003_3.geometry}
                material={materials.SAND}
                {...extras}
              />
            </group>
            <group
              name="TORSOMUSICDRUMKIT"
              position={[0, 0.04, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                name="Merged_Extract3"
                geometry={nodes.Merged_Extract3.geometry}
                material={materials["GREY DARK"]}
                {...extras}
              />
              <mesh
                name="Merged_Extract3_1"
                geometry={nodes.Merged_Extract3_1.geometry}
                material={materials["YELLOW ORANGE"]}
                {...extras}
              />
              <mesh
                name="Merged_Extract3_2"
                geometry={nodes.Merged_Extract3_2.geometry}
                material={materials["SAND SHADING"]}
                {...extras}
              />
              <mesh
                name="Merged_Extract3_3"
                geometry={nodes.Merged_Extract3_3.geometry}
                material={materials.RED}
                {...extras}
              />
              <mesh
                name="Merged_Extract3_4"
                geometry={nodes.Merged_Extract3_4.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
            </group>
            <group name="ARMS" position={[0, 0.04, 0]}>
              <mesh
                name="ARMS_1"
                geometry={nodes.ARMS_1.geometry}
                material={materials.GREY}
                {...extras}
              />
              <mesh
                name="ARMS_2"
                geometry={nodes.ARMS_2.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
            </group>
            <mesh
              name="BODY"
              geometry={nodes.BODY.geometry}
              material={materials.GREY}
              position={[0, 0.04, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
              {...extras}
            />
            <mesh
              name="EYES001"
              geometry={nodes.EYES001.geometry}
              material={materials["TENNIS BALL GREEN"]}
              position={[0, 0.04, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
              {...extras}
            />
            <mesh
              name="FEET"
              geometry={nodes.FEET.geometry}
              material={materials.GREY}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
              {...extras}
            />
            <group name="LEGS">
              <mesh
                name="Merged_Apple7006"
                geometry={nodes.Merged_Apple7006.geometry}
                material={materials.GREY}
                {...extras}
              />
              <mesh
                name="Merged_Apple7006_1"
                geometry={nodes.Merged_Apple7006_1.geometry}
                material={materials.OH_Outline_Material}
                {...extras}
              />
            </group>
            <mesh
              name="PUPILS"
              geometry={nodes.PUPILS.geometry}
              material={materials.OH_Outline_Material}
              position={[0, 0.04, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
              {...extras}
            />
          </group>
        </group>
        <group name="Armature">
          <group
            name="SPINE"
            position={[0, 0.09, -0.63]}
            rotation={[0.66, 0, 0]}
          >
            <group
              name="SHOULDER_L"
              position={[0, 0.74, 0]}
              rotation={[-0.66, 0.11, -1.72]}
            >
              <group
                name="ARM_1_L"
                position={[0, 0.47, 0]}
                rotation={[-1.5, -1.07, -1.58]}
              >
                <group
                  name="ARM_2_L"
                  position={[0, 0.71, 0]}
                  rotation={[1.09, -0.14, -0.76]}
                >
                  <group
                    name="ARM_3_L"
                    position={[0, 0.37, 0]}
                    rotation={[0.54, 0.13, -0.28]}
                  />
                </group>
              </group>
            </group>
            <group
              name="HEAD"
              position={[0, 1.07, -0.07]}
              rotation={[-0.56, 0, 0]}
            />
            <group
              name="LEG_1_L"
              position={[0.05, -0.01, -0.01]}
              rotation={[-1.7, 0.18, -2.32]}
            >
              <group
                name="LEG_2_L"
                position={[0, 0.45, 0]}
                rotation={[-0.13, 0.07, -0.12]}
              >
                <group
                  name="LEG_3_L"
                  position={[0, 0.68, 0]}
                  rotation={[1.03, 1.28, -2.23]}
                >
                  <group
                    name="ANKLE_L"
                    position={[0, 0.76, 0]}
                    rotation={[-0.18, -0.1, 1.17]}
                  />
                  <group
                    name="ANKLE_001_L"
                    position={[0, 0.76, 0]}
                    rotation={[-0.14, -0.17, 1.17]}
                  />
                </group>
              </group>
            </group>
            <group
              name="SHOULDER_R"
              position={[0, 0.74, 0]}
              rotation={[-0.66, -0.11, 1.73]}
            >
              <group
                name="ARM_1_R"
                position={[0, 0.47, 0]}
                rotation={[-1.5, 1.07, 1.58]}
              >
                <group
                  name="ARM_2_R"
                  position={[0, 0.71, 0]}
                  rotation={[1.09, 0.14, 0.76]}
                >
                  <group
                    name="ARM_3_R"
                    position={[0, 0.37, 0]}
                    rotation={[0.54, -0.13, 0.28]}
                  />
                </group>
              </group>
            </group>
            <group
              name="LEG_1_R"
              position={[-0.05, -0.01, -0.01]}
              rotation={[-1.7, -0.19, 2.32]}
            >
              <group
                name="LEG_2_R"
                position={[0, 0.45, 0]}
                rotation={[-0.13, -0.07, 0.12]}
              >
                <group
                  name="LEG_3_R"
                  position={[0, 0.68, 0]}
                  rotation={[1.03, -1.28, 2.23]}
                >
                  <group
                    name="ANKLE_R"
                    position={[0, 0.76, 0]}
                    rotation={[-0.18, 0.1, -1.17]}
                  />
                  <group
                    name="ANKLE_001_R"
                    position={[0, 0.76, 0]}
                    rotation={[-0.14, 0.17, -1.17]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d/jnrbox-transformed.glb");
