/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.7 .\jnrbox-2.glb --transform -R 2048 --types --keepnames --keepmeshes
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useBounds } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    BOX_FILM: THREE.Mesh;
    BOX_PLINTH: THREE.Mesh;
    Cube005: THREE.SkinnedMesh;
    Cube005_1: THREE.SkinnedMesh;
    Cube005_2: THREE.SkinnedMesh;
    Cube005_3: THREE.SkinnedMesh;
    DKFYB6: THREE.Mesh;
    DKFYB6_1: THREE.Mesh;
    DKFYB6_2: THREE.Mesh;
    DKFYB6_3: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002_1: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002_2: THREE.Mesh;
    Merged_PM3D_SHORTS1_2002_3: THREE.Mesh;
    Merged_Apple002: THREE.Mesh;
    Merged_Apple002_1: THREE.Mesh;
    Merged_Apple002_2: THREE.Mesh;
    Merged_Apple002_3: THREE.Mesh;
    Merged_Apple002_4: THREE.Mesh;
    Merged_JNRS_HANDS1: THREE.Mesh;
    Merged_JNRS_HANDS1_1: THREE.Mesh;
    Merged_JNRS_HANDS1_2: THREE.Mesh;
    Merged_JNRS_HANDS1_3: THREE.Mesh;
    Merged_JNRS_HANDS1_4: THREE.Mesh;
    Merged_JNRS_HANDS1_5: THREE.Mesh;
    Merged_JNRS_HANDS1_6: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_1: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_2: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_3: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_4: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_5: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_6: THREE.Mesh;
    Merged_RUBIKS_WINGS_2011_7: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003_1: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003_2: THREE.Mesh;
    Merged_PM3D_Cylinder3D1_2003_3: THREE.Mesh;
    Merged_Extract3: THREE.Mesh;
    Merged_Extract3_1: THREE.Mesh;
    Merged_Extract3_2: THREE.Mesh;
    Merged_Extract3_3: THREE.Mesh;
    Merged_Extract3_4: THREE.Mesh;
    ARMS_1: THREE.Mesh;
    ARMS_2: THREE.Mesh;
    BODY: THREE.Mesh;
    EYES001: THREE.Mesh;
    FEET: THREE.Mesh;
    Merged_Apple7006: THREE.Mesh;
    Merged_Apple7006_1: THREE.Mesh;
    PUPILS: THREE.Mesh;
    MAIN: THREE.Bone;
  };
  materials: {
    ["BOX FILM"]: THREE.MeshPhysicalMaterial;
    OUTLINE: THREE.MeshStandardMaterial;
    ["BOX MAIN"]: THREE.MeshStandardMaterial;
    CHROME: THREE.MeshStandardMaterial;
    ["BOX MAIN LID"]: THREE.MeshStandardMaterial;
    ["BOX MAIN INSIDE"]: THREE.MeshStandardMaterial;
    ["YELLOW ORANGE"]: THREE.MeshStandardMaterial;
    ["DARK GREY 3"]: THREE.MeshStandardMaterial;
    ["GREY DARK"]: THREE.MeshStandardMaterial;
    OH_Outline_Material: THREE.MeshBasicMaterial;
    ["GREEN EARTH DARK"]: THREE.MeshStandardMaterial;
    YELLOW: THREE.MeshStandardMaterial;
    ["GREEN EARTH"]: THREE.MeshStandardMaterial;
    ["OUTLINE GREEN"]: THREE.MeshBasicMaterial;
    ["SAND SHADING"]: THREE.MeshStandardMaterial;
    SAND: THREE.MeshStandardMaterial;
    ["OUTLINE RED"]: THREE.MeshStandardMaterial;
    RED: THREE.MeshStandardMaterial;
    WHITE: THREE.MeshStandardMaterial;
    GREY: THREE.MeshStandardMaterial;
    ORANGE: THREE.MeshStandardMaterial;
    ["HOT SKY BLUE"]: THREE.MeshStandardMaterial;
    ["GREEN LIGHT"]: THREE.MeshStandardMaterial;
    BRICK: THREE.MeshStandardMaterial;
    ["TENNIS BALL GREEN"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Animation";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

interface Props {
  groupProps?: JSX.IntrinsicElements["group"];
  scroll: React.MutableRefObject<number>;
}

export function JnrBox(props: Props) {
  const group = useRef<THREE.Group>();
  // const { scene, animations } = useGLTF("/3d/jnrbox-transformed.glb");
  const { nodes, materials, animations } = useGLTF(
    "/3d/jnr-box-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  const bounds = useBounds();

  useEffect(() => void (actions["Animation"].play().paused = true), []);

  useFrame((state) => {
    actions["Animation"].time = THREE.MathUtils.lerp(
      actions["Animation"].time,
      actions["Animation"].getClip().duration * props.scroll.current,
      0.05
    );
    group.current.children.forEach((child, index) => {
      const et = state.clock.elapsedTime;
      child.position.y = Math.sin((et + index * 2000) / 2) * 1;
      child.rotation.x = Math.sin((et + index * 2000) / 3) / 10;
      child.rotation.y = Math.cos((et + index * 2000) / 2) / 10;
      child.rotation.z = Math.sin((et + index * 2000) / 3) / 10;
    });
  });

  useEffect(() => {
    if (!group.current) return;
    bounds.refresh().fit().moveTo([0, -1, 15]);
  }, [group.current]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="BOX" position={[0, 2.85, -0.21]} scale={0.94}>
          <group name="BOX_OPENING_ARMATURE" position={[0, -0.68, -0.21]}>
            <primitive object={nodes.MAIN} />
            <mesh
              name="BOX_FILM"
              geometry={nodes.BOX_FILM.geometry}
              material={materials["BOX FILM"]}
              position={[0, -3.02, 0.22]}
            />
            <mesh
              name="BOX_PLINTH"
              geometry={nodes.BOX_PLINTH.geometry}
              material={materials.OUTLINE}
              position={[0, -3.02, 0.22]}
            />
            <group name="BOX_MAIN">
              <skinnedMesh
                name="Cube005"
                geometry={nodes.Cube005.geometry}
                material={materials["BOX MAIN"]}
                skeleton={nodes.Cube005.skeleton}
              />
              <skinnedMesh
                name="Cube005_1"
                geometry={nodes.Cube005_1.geometry}
                material={materials.CHROME}
                skeleton={nodes.Cube005_1.skeleton}
              />
              <skinnedMesh
                name="Cube005_2"
                geometry={nodes.Cube005_2.geometry}
                material={materials["BOX MAIN LID"]}
                skeleton={nodes.Cube005_2.skeleton}
              />
              <skinnedMesh
                name="Cube005_3"
                geometry={nodes.Cube005_3.geometry}
                material={materials["BOX MAIN INSIDE"]}
                skeleton={nodes.Cube005_3.skeleton}
              />
            </group>
          </group>
          <group name="JNRS" position={[0, -0.66, 0]}>
            <group name="JNR_1">
              <group name="BACKMUSICDRUMKIT">
                <mesh
                  name="DKFYB6"
                  geometry={nodes.DKFYB6.geometry}
                  material={materials["YELLOW ORANGE"]}
                />
                <mesh
                  name="DKFYB6_1"
                  geometry={nodes.DKFYB6_1.geometry}
                  material={materials["DARK GREY 3"]}
                />
                <mesh
                  name="DKFYB6_2"
                  geometry={nodes.DKFYB6_2.geometry}
                  material={materials["GREY DARK"]}
                />
                <mesh
                  name="DKFYB6_3"
                  geometry={nodes.DKFYB6_3.geometry}
                  material={materials.OH_Outline_Material}
                />
              </group>
              <group name="BOTTOMSHISTORYTREX">
                <mesh
                  name="Merged_PM3D_SHORTS1_2002"
                  geometry={nodes.Merged_PM3D_SHORTS1_2002.geometry}
                  material={materials.OH_Outline_Material}
                />
                <mesh
                  name="Merged_PM3D_SHORTS1_2002_1"
                  geometry={nodes.Merged_PM3D_SHORTS1_2002_1.geometry}
                  material={materials["GREEN EARTH DARK"]}
                />
                <mesh
                  name="Merged_PM3D_SHORTS1_2002_2"
                  geometry={nodes.Merged_PM3D_SHORTS1_2002_2.geometry}
                  material={materials.YELLOW}
                />
                <mesh
                  name="Merged_PM3D_SHORTS1_2002_3"
                  geometry={nodes.Merged_PM3D_SHORTS1_2002_3.geometry}
                  material={materials["GREEN EARTH"]}
                />
              </group>
              <group name="HEADMATHSPC">
                <mesh
                  name="Merged_Apple002"
                  geometry={nodes.Merged_Apple002.geometry}
                  material={materials.OH_Outline_Material}
                />
                <mesh
                  name="Merged_Apple002_1"
                  geometry={nodes.Merged_Apple002_1.geometry}
                  material={materials["OUTLINE GREEN"]}
                />
                <mesh
                  name="Merged_Apple002_2"
                  geometry={nodes.Merged_Apple002_2.geometry}
                  material={materials["SAND SHADING"]}
                />
                <mesh
                  name="Merged_Apple002_3"
                  geometry={nodes.Merged_Apple002_3.geometry}
                  material={materials.SAND}
                />
                <mesh
                  name="Merged_Apple002_4"
                  geometry={nodes.Merged_Apple002_4.geometry}
                  material={materials["OUTLINE RED"]}
                />
              </group>
              <group name="LHMATHSCLOCK">
                <mesh
                  name="Merged_JNRS_HANDS1"
                  geometry={nodes.Merged_JNRS_HANDS1.geometry}
                  material={materials.RED}
                />
                <mesh
                  name="Merged_JNRS_HANDS1_1"
                  geometry={nodes.Merged_JNRS_HANDS1_1.geometry}
                  material={materials.WHITE}
                />
                <mesh
                  name="Merged_JNRS_HANDS1_2"
                  geometry={nodes.Merged_JNRS_HANDS1_2.geometry}
                  material={materials["DARK GREY 3"]}
                />
                <mesh
                  name="Merged_JNRS_HANDS1_3"
                  geometry={nodes.Merged_JNRS_HANDS1_3.geometry}
                  material={materials.GREY}
                />
                <mesh
                  name="Merged_JNRS_HANDS1_4"
                  geometry={nodes.Merged_JNRS_HANDS1_4.geometry}
                  material={materials.WHITE}
                />
                <mesh
                  name="Merged_JNRS_HANDS1_5"
                  geometry={nodes.Merged_JNRS_HANDS1_5.geometry}
                  material={materials.YELLOW}
                />
                <mesh
                  name="Merged_JNRS_HANDS1_6"
                  geometry={nodes.Merged_JNRS_HANDS1_6.geometry}
                  material={materials.OH_Outline_Material}
                />
              </group>
              <group name="RHMATHSRUBIKS">
                <mesh
                  name="Merged_RUBIKS_WINGS_2011"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011.geometry}
                  material={materials.WHITE}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_1"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_1.geometry}
                  material={materials.OH_Outline_Material}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_2"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_2.geometry}
                  material={materials.ORANGE}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_3"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_3.geometry}
                  material={materials.RED}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_4"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_4.geometry}
                  material={materials.YELLOW}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_5"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_5.geometry}
                  material={materials["HOT SKY BLUE"]}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_6"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_6.geometry}
                  material={materials["DARK GREY 3"]}
                />
                <mesh
                  name="Merged_RUBIKS_WINGS_2011_7"
                  geometry={nodes.Merged_RUBIKS_WINGS_2011_7.geometry}
                  material={materials["GREEN LIGHT"]}
                />
              </group>
              <group name="SHOESBIOLOGYTIGER">
                <mesh
                  name="Merged_PM3D_Cylinder3D1_2003"
                  geometry={nodes.Merged_PM3D_Cylinder3D1_2003.geometry}
                  material={materials.BRICK}
                />
                <mesh
                  name="Merged_PM3D_Cylinder3D1_2003_1"
                  geometry={nodes.Merged_PM3D_Cylinder3D1_2003_1.geometry}
                  material={materials.OH_Outline_Material}
                />
                <mesh
                  name="Merged_PM3D_Cylinder3D1_2003_2"
                  geometry={nodes.Merged_PM3D_Cylinder3D1_2003_2.geometry}
                  material={materials["DARK GREY 3"]}
                />
                <mesh
                  name="Merged_PM3D_Cylinder3D1_2003_3"
                  geometry={nodes.Merged_PM3D_Cylinder3D1_2003_3.geometry}
                  material={materials.SAND}
                />
              </group>
              <group name="TORSOMUSICDRUMKIT">
                <mesh
                  name="Merged_Extract3"
                  geometry={nodes.Merged_Extract3.geometry}
                  material={materials["GREY DARK"]}
                />
                <mesh
                  name="Merged_Extract3_1"
                  geometry={nodes.Merged_Extract3_1.geometry}
                  material={materials["YELLOW ORANGE"]}
                />
                <mesh
                  name="Merged_Extract3_2"
                  geometry={nodes.Merged_Extract3_2.geometry}
                  material={materials["SAND SHADING"]}
                />
                <mesh
                  name="Merged_Extract3_3"
                  geometry={nodes.Merged_Extract3_3.geometry}
                  material={materials.RED}
                />
                <mesh
                  name="Merged_Extract3_4"
                  geometry={nodes.Merged_Extract3_4.geometry}
                  material={materials.OH_Outline_Material}
                />
              </group>
            </group>
            <group name="JNR_BASE">
              <group name="ARMS">
                <mesh
                  name="ARMS_1"
                  geometry={nodes.ARMS_1.geometry}
                  material={materials.GREY}
                />
                <mesh
                  name="ARMS_2"
                  geometry={nodes.ARMS_2.geometry}
                  material={materials.OH_Outline_Material}
                />
              </group>
              <mesh
                name="BODY"
                geometry={nodes.BODY.geometry}
                material={materials.GREY}
              />
              <mesh
                name="EYES001"
                geometry={nodes.EYES001.geometry}
                material={materials["TENNIS BALL GREEN"]}
              />
              <mesh
                name="FEET"
                geometry={nodes.FEET.geometry}
                material={materials.GREY}
              />
              <group name="LEGS">
                <mesh
                  name="Merged_Apple7006"
                  geometry={nodes.Merged_Apple7006.geometry}
                  material={materials.GREY}
                />
                <mesh
                  name="Merged_Apple7006_1"
                  geometry={nodes.Merged_Apple7006_1.geometry}
                  material={materials.OH_Outline_Material}
                />
              </group>
              <mesh
                name="PUPILS"
                geometry={nodes.PUPILS.geometry}
                material={materials.OH_Outline_Material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
